### PR TITLE
build: use NPM packages instead of git submodules

### PR DESCRIPTION
**Pull request by andreivladbrg**
Switches from installing `v2-core` as a git module to installing it as a NPM package.

### CODE REVIEW

**Review by PaulRBerg — APPROVED** [review]
Thanks, this is great.

We can also install `forge-std` as a Node.js package from GitHub.

**Comment by andreivladbrg** [comment]
> We can also install forge-std as a Node.js package from GitHub.

I've asked about this [here](https://github.com/PaulRBerg/prb-math/pull/206#issuecomment-1775918183)

**Comment by PaulRBerg** [comment]
I wasn't able to use Forge Std as a Node.js package, so I think this is not a question of preference but of necessity. We will keep installing Forge Std from git submodules.

https://github.com/foundry-rs/forge-std/issues/208#issuecomment-1783027182

**Comment by PaulRBerg** [comment]
> It shouldn't be a "necessity":

See https://github.com/foundry-rs/forge-std/issues/208#issuecomment-1783027182

**Comment by PaulRBerg** [comment]
Don't think you looked at the latest CI run, @andreivladbrg.

**Comment by andreivladbrg** [comment]
Still not a "necessity". This can be fixed by adding this [remappings](https://github.com/sablier-labs/sablier-v2-integration-template/blob/e55ec4a7e09931659959dc0f93723e0d82c8f3f2/remappings.txt#L1). You can run locally [this branch](https://github.com/sablier-labs/sablier-v2-integration-template/tree/build/foundry-npm): https://app.warp.dev/block/MtrSbAaMRDnU5ZrsyFFLul

A easier fix would be to import in `forge-std` from: `import {DSTest} from "../src/ds-test/test.sol";`

Anyway, I am not in favor in installing forge-std as NPM, as said in my [initial comment](https://github.com/PaulRBerg/prb-math/pull/206#issuecomment-1775918183).

**Comment by PaulRBerg** [comment]
> Still not a "necessity". This can be fixed by adding this remappings

Ah, yes. Remappings for DSTest! Good point.

**Pull request merged**
